name: Terraform NGINX

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

