name: Terraform NGINX

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      working-directory: terraform
    defaults:
      run:
        working-directory: terraform
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform init
        run: terraform init

      - name: Terraform validation
        run: terraform validate

      - name: Terrafom Format
        run: terraform fmt -check

      - name: TFLint
        uses: github.com/terraform-linters/tflint@latest
        with: 
          terraform_version: 1.5.0

      - name: Terraform Plan
        run: terraform plan

